import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/app/lib/prisma";

export async function POST(
  req: NextRequest,
  context: { params: { id: string } }
) {
  const { id } = context.params;

  const { thresholds } = await req.json();

  const existing = await prisma.question.findUnique({
    where: { id },
    include: { scoringModel: true },
  });

  let result;

  if (existing?.scoringModel) {
    result = await prisma.scoringModel.update({
      where: { id: existing.scoringModel.id },
      data: { thresholds },
    });
  } else {
    const scoringModel = await prisma.scoringModel.create({
      data: {
        name: "AutoGenerated",
        thresholds,
      },
    });

    result = await prisma.question.update({
      where: { id },
      data: {
        scoringModelId: scoringModel.id,
      },
    });
  }

  return NextResponse.json(result);
}
